version: '3'
services:
  database:
    container_name: "database_postgres"
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: "always"
    networks:
      backendnet:

  keycloak:
    container_name: "keycloak"
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_IMPORT: /tmp/realm-import.json -Dkeycloak.profile.feature.upload_scripts=enabled
      DB_VENDOR: POSTGRES
      DB_ADDR: database
      DB_DATABASE: bis
      DB_USER: bis
      DB_SCHEMA: keycloak
      DB_PASSWORD: bis
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    volumes:
      - ./realm-import1.json:/tmp/realm-import.json
    ports:
      - "8180:8080"
    depends_on:
      - database
    networks:
      backendnet:

  minio:
    container_name: "minio"
    image: minio/minio:latest
    volumes:
      - minio-data:/data
    command: "server --console-address :9001 /minio-data"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    networks:
      backendnet:


volumes:
  minio-data:
  database-data:

networks:
  backendnet:
    driver: bridge
